name: build_deploy_aws

on:
  push:
    branches: ["master"]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22'  # Specify the Node.js version you need

      - name: Build Docker image
        run: docker build -t anirban1507/myfirstnext:latest .

      - name: Docker login
        run: docker login -u "${{secrets.DOCKER_HUB_USERNAME}}" -p "${{secrets.DOCKER_HUB_PWD}}"

      - name: Docker push
        run: docker push anirban1507/myfirstnext:latest     
          
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: "${{secrets.AWS_EC2_PEM_KEY}}"

      - name: login to aws ec2 and check docker
        run: |
            ssh -o StrictHostKeyChecking=no "${{secrets.AWS_EC2_CONNECTION_STRING}}" << 'EOF'
            sudo docker info
            EOF

        
