name: build_deploy_aws

on:
  push:
    branches: ["master"]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.3
        with:
          node-version: '22'  # Specify the Node.js version you need

      - name: Build Docker image
        run: docker build -t anirban1507/myfirstnext:latest .

      - name: Docker login
        run: docker login -u "${{secrets.DOCKER_HUB_USERNAME}}" -p "${{secrets.DOCKER_HUB_PWD}}"

      - name: Docker push
        run: docker push anirban1507/myfirstnext:latest     
          
      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: "${{secrets.AWS_EC2_PEM_KEY}}"

      - name: login to aws ec2 and check docker
        run: |
            ssh -o StrictHostKeyChecking=no "${{secrets.AWS_EC2_CONNECTION_STRING}}" << 'EOF'
            #!/bin/bash
            SERVICE_NAME="my-first-next-app"       # The name of the service you want to create or update
            IMAGE_NAME="anirban1507/myfirstnext:latest"     # The Docker image to use for the service
            PUBLISHED_PORT="8080"           # The port on the host machine
            CONTAINER_PORT="3000"

            SERVICE_EXISTS=$(docker service ls --filter "name=$SERVICE_NAME" --format "{{.Name}}")
            if [ "$SERVICE_EXISTS" == "$SERVICE_NAME" ]; then
               echo "Service $SERVICE_NAME already exists. Updating the service..."

            # Update the existing service with the new image
              sudo docker service update --image $IMAGE_NAME $SERVICE_NAME

             if [ $? -eq 0 ]; then
                echo "Service $SERVICE_NAME updated successfully."
             else
                echo "Failed to update service $SERVICE_NAME."
             exit 1
             fi

             else
                echo "Service $SERVICE_NAME does not exist. Creating a new service..."

            # Create a new service
            sudo docker service create --name $SERVICE_NAME --publish $PUBLISHED_PORT:$CONTAINER_PORT $IMAGE_NAME

            if [ $? -eq 0 ]; then
                echo "Service $SERVICE_NAME created successfully."
            else
                echo "Failed to create service $SERVICE_NAME."
            exit 1
            fi
            fi
            EOF

        
